In [1]:
import pandas as pd
import numpy as np
import datetime

In [2]:
data=pd.read_csv(r'./data.csv',encoding='gbk')

In [3]:
data

,Unnamed: 0,custid,trade_no,bank_card_no,low_volume_percent,middle_volume_percent,take_amount_in_later_12_month_highest,trans_amount_increase_rate_lately,trans_activity_month,trans_activity_day,...,loans_max_limit,loans_avg_limit,consfin_credit_limit,consfin_credibility,consfin_org_count_current,consfin_product_count,consfin_max_limit,consfin_avg_limit,latest_query_day,loans_latest_day
0,5,2791858,20180507115231274000000023057383,卡号1,0.01,0.99,0,0.90,0.55,0.313,...,2900.0,1688.0,1200.0,75.0,1.0,2.0,1200.0,1200.0,12.0,18.0
1,10,534047,20180507121002192000000023073000,卡号1,0.02,0.94,2000,1.28,1.00,0.458,...,3500.0,1758.0,15100.0,80.0,5.0,6.0,22800.0,9360.0,4.0,2.0
2,12,2849787,20180507125159718000000023114911,卡号1,0.04,0.96,0,1.00,1.00,0.114,...,1600.0,1250.0,4200.0,87.0,1.0,1.0,4200.0,4200.0,2.0,6.0
3,13,1809708,20180507121358683000000388283484,卡号1,0.00,0.96,2000,0.13,0.57,0.777,...,3200.0,1541.0,16300.0,80.0,5.0,5.0,30000.0,12180.0,2.0,4.0
4,14,2499829,20180507115448545000000388205844,卡号1,0.01,0.99,0,0.46,1.00,0.175,...,2300.0,1630.0,8300.0,79.0,2.0,2.0,8400.0,8250.0,22.0,120.0
5,15,518072,20180507121233054000000388275132,卡号1,0.02,0.98,2000,7.59,1.00,0.733,...,5300.0,1941.0,11200.0,80.0,10.0,12.0,20400.0,8130.0,3.0,4.0
6,16,1205125,20180507121931540000000388298915,卡号1,0.02,0.98,0,23.67,0.94,0.087,...,2200.0,2200.0,7600.0,73.0,2.0,2.0,16800.0,8900.0,1.0,3.0
7,18,1129897,20180507124659235000000023105807,卡号1,0.02,0.98,0,0.25,0.88,0.302,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,20,2599411,20180507115855621000000388224458,卡号1,0.03,0.65,0,0.31,0.76,0.472,...,5300.0,4750.0,5500.0,79.0,8.0,11.0,19200.0,7987.0,24.0,7.0
9,26,1413051,20180504155156296000000021138084,卡号1,0.01,0.99,500,0.80,1.00,0.088,...,2800.0,1520.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0,142.0
10,28,321061,20180507123917136000000388381264,卡号1,0.01,0.99,0,2.48,0.94,0.322,...,1800.0,1325.0,9900.0,80.0,7.0,8.0,20400.0,7757.0,12.0,9.0
11,29,750939,20180507121556599000000023080022,卡号1,0.01,0.99,500,0.72,0.63,0.450,...,3900.0,2450.0,8300.0,85.0,3.0,3.0,13200.0,9400.0,31.0,35.0
12,30,1169544,20180507114604230000000388176931,卡号1,0.00,0.73,5000,0.09,0.70,0.697,...,3500.0,2000.0,19300.0,79.0,7.0,8.0,42000.0,16985.0,38.0,6.0
13,33,193188,20180507115807011000000388215609,卡号1,0.01,0.79,0,1.24,1.00,0.447,...,9300.0,2240.0,5000.0,83.0,5.0,7.0,11400.0,5460.0,13.0,9.0
14,37,1780401,20180507121351317000000388282601,卡号1,0.01,0.89,4000,0.07,1.00,0.233,...,2000.0,1600.0,0.0,0.0,0.0,0.0,0.0,0.0,16.0,193.0
15,41,999803,20180507120312643000000388240340,卡号1,0.01,0.99,0,1.13,0.76,0.480,...,4100.0,2633.0,18400.0,79.0,9.0,11.0,33600.0,17633.0,4.0,27.0
16,43,203427,20180507115358209000000388203669,卡号1,0.02,0.98,0,0.21,1.00,0.247,...,4500.0,2480.0,21300.0,77.0,4.0,4.0,27600.0,9900.0,3.0,1.0
17,46,829745,20180507123013060000000388346445,卡号1,0.02,0.98,300,0.60,0.43,0.355,...,2000.0,1575.0,4700.0,80.0,8.0,10.0,6600.0,4062.0,9.0,7.0
18,48,818730,20180507123317625000000388359399,卡号1,0.01,0.99,2000,0.87,1.00,0.377,...,5000.0,2533.0,10100.0,78.0,4.0,4.0,15600.0,10275.0,26.0,77.0
19,49,2318583,20180507122754609000000388339559,卡号1,0.01,0.96,0,1.37,0.51,0.486,...,6200.0,1957.0,10100.0,79.0,8.0,9.0,20400.0,8187.0,12.0,37.0
20,50,2770676,20180507114736098000000388185623,卡号1,0.02,0.98,300,0.11,1.00,0.229,...,500.0,500.0,8400.0,74.0,1.0,1.0,8400.0,8400.0,3.0,71.0
21,52,2763960,20180507122338228000000023086166,卡号1,0.02,0.98,0,0.43,0.66,0.369,...,2400.0,1633.0,16500.0,76.0,2.0,3.0,32400.0,18600.0,7.0,23.0
22,53,1272880,20180504181611848000000381832460,卡号1,0.00,0.59,0,3.48,0.92,0.255,...,9000.0,3080.0,21900.0,79.0,11.0,11.0,39600.0,20454.0,4.0,1.0
23,60,800080,20180507123855945000000388380951,卡号1,0.01,0.99,2400,1.71,0.57,0.388,...,3500.0,1900.0,8100.0,80.0,6.0,7.0,14400.0,6100.0,12.0,9.0
24,61,654993,20180507123355168000000388361170,卡号1,0.02,0.78,2500,1.90,0.83,0.336,...,1000.0,750.0,14000.0,75.0,3.0,3.0,31200.0,15500.0,14.0,104.0
25,62,140303,20180504162411113000000021172853,卡号1,0.40,0.60,0,1.46,0.69,0.375,...,5000.0,1560.0,10400.0,78.0,12.0,14.0,42600.0,9841.0,21.0,82.0
26,64,148742,20180507120445507000000388245413,卡号1,0.02,0.96,0,12.35,0.96,0.444,...,2500.0,1671.0,6500.0,77.0,2.0,2.0,8100.0,7050.0,10.0,80.0
27,71,713652,20180507123830326000000388380639,卡号1,0.01,0.91,2000,46.90,0.69,0.263,...,5700.0,3160.0,7000.0,78.0,13.0,15.0,13200.0,6461.0,20.0,6.0
28,80,3051745,20180507115610811000000388212340,卡号1,0.01,0.99,3000,0.91,0.93,0.305,...,2700.0,1825.0,21600.0,78.0,1.0,1.0,21600.0,21600.0,5.0,9.0
29,88,1870891,20180507123310399000000388357579,卡号1,0.02,0.64,1500,1.02,0.44,0.211,...,2000.0,2000.0,3000.0,79.0,1.0,1.0,3000.0,3000.0,NaN,34.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4724,11923,3401661,20180507124934620000000388416059,卡号1,0.02,0.98,1000,1.37,0.89,0.287,...,3800.0,2271.0,5000.0,79.0,5.0,6.0,9000.0,3460.0,21.0,5.0
4725,11924,3089430,20180507122940057000000388342910,卡号1,0.01,0.99,0,0.28,0.57,0.137,...,2100.0,1166.0,17200.0,78.0,4.0,4.0,21600.0,11850.0,142.0,100.0
4726,11926,2123865,20180504162011976000000381367953,卡号1,0.00,1.00,900,1.60,0.90,0.250,...,3000.0,1960.0,4800.0,75.0,1.0,1.0,4800.0,4800.0,19.0,53.0
4727,11927,295148,20180507114821935000000388187853,卡号1,0.02,0.98,0,1.33,0.82,0.341,...,3100.0,1812.0,4800.0,76.0,4.0,4.0,12000.0,5125.0,28.0,57.0
4728,11930,2944213,20180507120905394000000023072119,卡号1,0.06,0.94,1500,4.70,1.00,0.444,...,2500.0,1662.0,10800.0,80.0,6.0,6.0,20400.0,8933.0,18.0,9.0
4729,11932,1757011,20180507123942186000000388381507,卡号1,0.17,0.83,0,0.88,1.00,0.316,...,2500.0,1518.0,6200.0,80.0,4.0,4.0,16800.0,7200.0,3.0,104.0
4730,11933,3380919,20180507124818814000000388411045,卡号1,0.01,0.99,2000,0.54,0.44,0.215,...,3100.0,1771.0,15600.0,78.0,1.0,1.0,15600.0,15600.0,28.0,128.0
4731,11936,1517438,20180507123928918000000388381394,卡号1,0.00,0.58,2000,2.63,0.73,0.525,...,3100.0,1818.0,60200.0,78.0,13.0,15.0,124200.0,25361.0,2.0,11.0
4732,11938,3382649,20180507124249332000000388393507,卡号1,0.11,0.89,4000,49.37,1.00,0.115,...,0.0,0.0,4300.0,80.0,2.0,2.0,7200.0,4950.0,9.0,250.0
4733,11940,2867902,20180507114636248000000388181870,卡号1,0.03,0.97,1000,2.98,0.88,0.255,...,4700.0,2320.0,9000.0,81.0,3.0,3.0,13200.0,6900.0,14.0,9.0
4734,11941,2854394,20180507124936647000000388418873,卡号1,0.00,1.00,0,1.06,0.85,0.221,...,3100.0,1950.0,1500.0,78.0,1.0,1.0,1500.0,1500.0,24.0,131.0
4735,11945,2722837,20180507121900401000000388295882,卡号1,0.01,0.61,5000,1.15,0.61,0.197,...,4100.0,1750.0,20300.0,79.0,4.0,4.0,34800.0,21100.0,2.0,6.0
4736,11947,3205825,20180507124233969000000023103541,卡号1,0.05,0.95,2000,2.39,1.00,0.207,...,1200.0,850.0,10200.0,85.0,1.0,1.0,10200.0,10200.0,18.0,156.0
4737,11950,11985,20180504170134092000000381539852,卡号1,0.01,0.99,300,1.00,0.46,0.547,...,3700.0,1757.0,14800.0,78.0,7.0,8.0,20400.0,11714.0,1.0,7.0
4738,11953,471607,20180507114726030000000023048892,卡号1,0.02,0.98,0,6.14,0.89,0.133,...,900.0,900.0,6800.0,79.0,2.0,3.0,7200.0,5700.0,48.0,89.0
4739,11957,3196970,20180504161419403000000381329175,卡号1,0.05,0.62,2400,0.28,0.67,0.403,...,2300.0,1766.0,3800.0,72.0,3.0,3.0,3900.0,3600.0,12.0,9.0
4740,11958,2154764,20180507115324523000000388201054,卡号1,0.07,0.93,9100,0.71,1.00,0.277,...,3900.0,2200.0,11300.0,79.0,3.0,3.0,12000.0,9200.0,31.0,163.0
4741,11959,490919,20180504183705135000000381895535,卡号1,0.00,0.83,3000,0.54,1.00,0.441,...,2300.0,2300.0,13700.0,80.0,3.0,3.0,19800.0,13900.0,9.0,140.0
4742,11964,2404717,20180507125018925000000023111153,卡号1,0.02,0.98,11300,0.39,0.96,0.525,...,4200.0,1928.0,9200.0,77.0,7.0,8.0,21600.0,7557.0,4.0,4.0
4743,11967,2475139,20180504170654830000000381561522,卡号1,0.00,1.00,0,0.84,1.00,0.372,...,3500.0,1825.0,1700.0,72.0,2.0,2.0,3600.0,2300.0,11.0,12.0
4744,11968,1039579,20180507115029481000000388194850,卡号1,0.01,0.96,0,0.89,0.45,0.405,...,3000.0,1691.0,5200.0,77.0,9.0,11.0,8400.0,3344.0,5.0,88.0
4745,11969,3361286,20180507123619864000000388369012,卡号1,0.04,0.96,400,0.79,0.67,0.348,...,2100.0,1280.0,6800.0,82.0,4.0,4.0,7200.0,5850.0,1.0,8.0
4746,11972,692541,20180507125012243000000023109396,卡号1,0.01,0.91,1600,1.04,0.82,0.541,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4747,11974,1886940,20180507123811494000000388377504,卡号1,0.02,0.40,0,1.08,0.94,0.394,...,1100.0,1100.0,4500.0,76.0,5.0,6.0,6000.0,3260.0,1.0,22.0
4748,11977,1663311,20180507121025853000000388266701,卡号1,0.09,0.91,0,0.15,0.20,0.159,...,3100.0,2450.0,17300.0,75.0,2.0,2.0,19800.0,18300.0,35.0,54.0
4749,11978,3269862,20180507120519228000000388247328,卡号1,0.05,0.68,1000,0.87,0.94,0.150,...,0.0,0.0,49200.0,78.0,1.0,1.0,49200.0,49200.0,44.0,58.0
4750,11986,270952,20180507114937914000000388192877,卡号1,0.01,0.99,400,0.93,0.98,0.605,...,5000.0,1952.0,10100.0,78.0,7.0,8.0,19200.0,7500.0,17.0,55.0
4751,11988,2425913,20180507121340509000000388278785,卡号1,0.00,1.00,3000,0.54,0.64,0.313,...,3300.0,1540.0,7600.0,79.0,8.0,8.0,21000.0,7250.0,18.0,55.0
4752,11991,471395,20180504161827128000000381357758,卡号1,0.05,0.95,0,4.79,1.00,0.458,...,1900.0,1216.0,7100.0,79.0,8.0,11.0,12000.0,3950.0,55.0,16.0
4753,11992,1881943,20180507124243041000000388391027,卡号1,0.01,0.99,1300,21.35,1.00,0.372,...,4000.0,2180.0,4500.0,74.0,5.0,5.0,7800.0,4360.0,20.0,54.0

In [5]:
#筛选X与Y

In [4]:
X= data.drop(columns=['status'],inplace=False)

In [7]:
X.shape[1]

89

In [5]:
#数据预处理
data.drop(index=list(data[data['latest_query_time'].isnull()].index),axis=0,inplace=True)
data.drop(index=list(data[data['loans_latest_time'].isnull()].index),axis=0,inplace=True)
latest_query_time_days=[]
loans_latest_time_days=[]
for i in data.index:
    a=datetime.datetime.strptime(data['trade_no'][i][0:4]+'-'+data['trade_no'][i][4:6]+'-'+data['trade_no'][i][6:8],'%Y-%m-%d')-datetime.datetime.strptime(data['latest_query_time'][i],'%Y-%m-%d')
    b=datetime.datetime.strptime(data['trade_no'][i][0:4]+'-'+data['trade_no'][i][4:6]+'-'+data['trade_no'][i][6:8],'%Y-%m-%d')-datetime.datetime.strptime(data['loans_latest_time'][i],'%Y-%m-%d')
    latest_query_time_days.append(a.days)
    loans_latest_time_days.append(b.days)
data['latest_query_time_days']=latest_query_time_days
data['loans_latest_time_days']=loans_latest_time_days
data.drop(columns=['latest_query_time','loans_latest_time'],axis=1,inplace=True)

In [6]:
#删除订单号
data.drop(columns=['trade_no'],axis=1,inplace=True)
data.drop(columns=['id_name','bank_card_no','source'],axis=1,inplace=True)

In [10]:
pd.value_counts(data['status'])

0    3317
1    1114
Name: status, dtype: int64

In [7]:
data[['reg_preference_for_trad','status']].groupby(data['reg_preference_for_trad']).status.count().reset_index()

  reg_preference_for_trad  status
0                    一线城市    3173
1                    三线城市     991
2                    二线城市     123
3                    其他城市       4
4                      境外     138

In [8]:
#计算离散型变量的IV,
def calc_iv_object(Y,X):
    dframe = pd.DataFrame({'X':X,'Y':Y})
    dframe.dropna(inplace=True)
    total_bad = dframe[dframe['Y']==1].shape[0]
    total_good =dframe[dframe['Y']==0].shape[0]
    dframe_group_bad = dframe.groupby(['X']).Y.sum().reset_index()
    dframe_group_bad.columns=['X_1','group_bad']
    dframe_group_total = dframe.groupby(['X']).Y.count().reset_index()
    dframe_group_total.columns=['X_2','group_total']
    dframe_merge=pd.merge(dframe_group_bad,dframe_group_total,how='left',left_on=['X_1'],right_on=['X_2'])
    dframe_merge['good']=dframe_merge['group_total']-dframe_merge['group_bad']
    dframe_merge['WOE']=np.log((dframe_merge['group_bad']/total_bad)/(dframe_merge['good']/total_good))
    dframe_merge['IV']=((dframe_merge['group_bad']/total_bad)-(dframe_merge['good']/total_good))*dframe_merge['WOE']
    return np.sum(dframe_merge['IV'].values)

In [9]:
calc_iv_object(data['status'],data['reg_preference_for_trad'])

0.007221885264242417

In [10]:
obj_frame = data.select_dtypes('object')

In [11]:
pd.get_dummies(data['reg_preference_for_trad'])

      一线城市  三线城市  二线城市  其他城市  境外
0        1     0     0     0   0
1        1     0     0     0   0
2        1     0     0     0   0
3        0     1     0     0   0
4        1     0     0     0   0
5        0     1     0     0   0
6        1     0     0     0   0
8        0     1     0     0   0
9        1     0     0     0   0
10       1     0     0     0   0
11       1     0     0     0   0
12       0     1     0     0   0
13       1     0     0     0   0
14       1     0     0     0   0
15       1     0     0     0   0
16       0     0     0     0   1
17       1     0     0     0   0
18       0     0     0     0   1
19       1     0     0     0   0
20       1     0     0     0   0
21       1     0     0     0   0
22       0     0     0     0   1
23       0     1     0     0   0
24       1     0     0     0   0
25       0     0     0     0   1
26       1     0     0     0   0
27       0     1     0     0   0
28       1     0     0     0   0
30       0     1     0     0   0
31       1     0     0     0   0
...    ...   ...   ...   ...  ..
4723     1     0     0     0   0
4724     1     0     0     0   0
4725     1     0     0     0   0
4726     0     0     0     0   1
4727     1     0     0     0   0
4728     1     0     0     0   0
4729     1     0     0     0   0
4730     0     1     0     0   0
4731     0     1     0     0   0
4732     1     0     0     0   0
4733     0     0     1     0   0
4734     0     0     0     0   1
4735     1     0     0     0   0
4736     1     0     0     0   0
4737     1     0     0     0   0
4738     1     0     0     0   0
4739     0     1     0     0   0
4740     1     0     0     0   0
4741     1     0     0     0   0
4742     1     0     0     0   0
4743     0     1     0     0   0
4744     1     0     0     0   0
4745     0     1     0     0   0
4747     0     0     0     0   1
4748     1     0     0     0   0
4749     1     0     0     0   0
4750     1     0     0     0   0
4751     1     0     0     0   0
4752     1     0     0     0   0
4753     1     0     0     0   0

[4431 rows x 5 columns]

In [12]:
import scipy.stats.stats as stats

In [13]:
#连续性变量先要分箱，这里用等频分箱
def calc_iv_num(Y,X,n=10):
    X2=X.fillna(np.median(X))
    r=0
    while np.abs(r)<1:
        d1=pd.DataFrame({'X':X2,'Y':Y,'bucket':pd.qcut(X2,n,duplicates='drop')})
        d2=d1.groupby('bucket',as_index=True)
        r,p=stats.spearmanr(d2.mean().X,d2.mean().Y)
        n -=1
    total_good =d1[d1['Y']==0].shape[0]
    total_bad = d1[d1['Y']==1].shape[0]
    dframe_group_bad=d1.groupby(['bucket']).Y.sum().reset_index()
    dframe_group_bad.columns=['bucket','bad']
    dframe_group_total=d1.groupby(['bucket']).Y.count().reset_index()
    dframe_group_total.columns=['bucket','total']
    dframe_merge=pd.merge(dframe_group_bad,dframe_group_total,how='left',left_on=['bucket'],right_on=['bucket'])
    dframe_merge['good']=dframe_merge['total']-dframe_merge['bad']
    dframe_merge['WOE']=np.log((dframe_merge['bad']/total_bad)/(dframe_merge['good']/total_good))
    dframe_merge['IV']=((dframe_merge['bad']/total_bad-dframe_merge['good']/total_good))*dframe_merge['WOE']
    return np.sum(dframe_merge['IV'].values)

In [14]:
data_test=data[['middle_volume_percent','status']]

In [21]:
data_test['middle_volume_percent'].unique()

array([0.99, 0.94, 0.96, 0.98, 0.65, 0.73, 0.79, 0.89, 0.59, 0.78, 0.6 ,
       0.91, 0.93, 0.97, 0.67, 1.  , 0.92, 0.95, 0.88, 0.82, 0.84, 0.8 ,
       0.76, 0.9 , 0.77, 0.63, 0.87, 0.48, 0.15, 0.74, 0.72, 0.55, 0.83,
       0.68, 0.75, 0.85, 0.45, 0.56, 0.39, 0.44, 0.54, 0.49, 0.53, 0.86,
       0.2 , 0.64, 0.11, 0.37, 0.7 , 0.62, 0.69, 0.81, 0.52, 0.71, 0.28,
       0.19, 0.38, 0.  , 0.12, 0.57, 0.5 , 0.58, 0.4 , 0.66, 0.43, 0.36,
       0.31, 0.16, 0.47, 0.51, 0.29, 0.61, 0.3 , 0.05, 0.08, 0.22, 0.34,
       0.14, 0.41, 0.46, 0.35,  nan, 0.42, 0.26, 0.32, 0.21, 0.27, 0.33,
       0.25, 0.09, 0.06])

In [22]:
pd.DataFrame({'X':data_test['middle_volume_percent'],'Y':data_test['status'],'bu':pd.qcut(data_test['middle_volume_percent'],5,duplicates='drop')})

         X  Y              bu
0     0.99  1    (0.97, 0.99]
1     0.94  0    (0.85, 0.94]
2     0.96  1    (0.94, 0.97]
3     0.96  0    (0.94, 0.97]
4     0.99  1    (0.97, 0.99]
5     0.98  0    (0.97, 0.99]
6     0.98  0    (0.97, 0.99]
8     0.65  0  (-0.001, 0.85]
9     0.99  1    (0.97, 0.99]
10    0.99  1    (0.97, 0.99]
11    0.99  0    (0.97, 0.99]
12    0.73  0  (-0.001, 0.85]
13    0.79  0  (-0.001, 0.85]
14    0.89  1    (0.85, 0.94]
15    0.99  1    (0.97, 0.99]
16    0.98  1    (0.97, 0.99]
17    0.98  0    (0.97, 0.99]
18    0.99  0    (0.97, 0.99]
19    0.96  1    (0.94, 0.97]
20    0.98  1    (0.97, 0.99]
21    0.98  0    (0.97, 0.99]
22    0.59  0  (-0.001, 0.85]
23    0.99  0    (0.97, 0.99]
24    0.78  0  (-0.001, 0.85]
25    0.60  1  (-0.001, 0.85]
26    0.96  0    (0.94, 0.97]
27    0.91  0    (0.85, 0.94]
28    0.99  0    (0.97, 0.99]
30    0.93  0    (0.85, 0.94]
31    0.98  0    (0.97, 0.99]
...    ... ..             ...
4723  0.96  0    (0.94, 0.97]
4724  0.98  1    (0.97, 0.99]
4725  0.99  0    (0.97, 0.99]
4726  1.00  0     (0.99, 1.0]
4727  0.98  0    (0.97, 0.99]
4728  0.94  0    (0.85, 0.94]
4729  0.83  0  (-0.001, 0.85]
4730  0.99  1    (0.97, 0.99]
4731  0.58  0  (-0.001, 0.85]
4732  0.89  0    (0.85, 0.94]
4733  0.97  1    (0.94, 0.97]
4734  1.00  1     (0.99, 1.0]
4735  0.61  1  (-0.001, 0.85]
4736  0.95  0    (0.94, 0.97]
4737  0.99  1    (0.97, 0.99]
4738  0.98  1    (0.97, 0.99]
4739  0.62  0  (-0.001, 0.85]
4740  0.93  0    (0.85, 0.94]
4741  0.83  0  (-0.001, 0.85]
4742  0.98  0    (0.97, 0.99]
4743  1.00  0     (0.99, 1.0]
4744  0.96  1    (0.94, 0.97]
4745  0.96  0    (0.94, 0.97]
4747  0.40  0  (-0.001, 0.85]
4748  0.91  0    (0.85, 0.94]
4749  0.68  1  (-0.001, 0.85]
4750  0.99  0    (0.97, 0.99]
4751  1.00  0     (0.99, 1.0]
4752  0.95  0    (0.94, 0.97]
4753  0.99  0    (0.97, 0.99]

[4431 rows x 3 columns]

In [17]:
data_num=data.select_dtypes(['int64','float64'])

In [18]:
data_num.drop(columns=['Unnamed: 0','custid'],inplace=True)

F:\anaconda\lib\site-packages\pandas\core\frame.py:3694: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)

In [19]:
dic={}
for i in data_num.columns:
    iv=calc_iv_num(data['status'],data[i],n=10)
    dic[i]=iv

F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)
F:\anaconda\lib\site-packages\numpy\lib\function_base.py:3405: RuntimeWarning: Invalid value encountered in median
  r = func(a, **kwargs)

In [20]:
data_analy=pd.DataFrame({'feature':list(dic.keys()),'iv':list(dic.values())})

In [21]:
data_analy[data_analy['iv']>=0.05]

                                    feature        iv
17                        rank_trad_1_month  0.109595
21             top_trans_count_last_1_month  0.064575
29   trans_fail_top_count_enum_last_1_month  0.569046
30   trans_fail_top_count_enum_last_6_month  0.221984
31  trans_fail_top_count_enum_last_12_month  0.200657
33     max_cumulative_consume_later_1_month  0.085743
41                  trans_day_last_12_month  0.097987
42                              apply_score  0.404976
51                              loans_score  0.478028
55                      loans_overdue_count  0.389096
63                         history_fail_fee  0.567060
64                     latest_one_month_suc  0.112486
65                    latest_one_month_fail  0.262168
78                        consfin_avg_limit  0.058658

In [22]:
data=pd.concat([data,pd.get_dummies(data['reg_preference_for_trad'])],axis=0)

F:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=True'.

To retain the current behavior and silence the warning, pass sort=False

  """Entry point for launching an IPython kernel.

In [23]:
data.drop(columns=['reg_preference_for_trad'],axis=1,inplace=True)

In [24]:
from sklearn.ensemble import RandomForestClassifier

F:\anaconda\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [25]:
#随机森林筛选特征
clf = RandomForestClassifier(n_jobs=2)
for i in data.columns:
    value=data[i].value_counts().index[0]
    data[i].fillna(value,inplace=True)
feature = data.drop(columns=['status'],axis=1,inplace=False).as_matrix()
target = data['status'].values
clf.fit(feature, target)

F:\anaconda\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [26]:
clf.feature_importances_

array([1.52927524e-02, 1.82623607e-02, 1.04108638e-02, 3.71750032e-02,
       5.23638657e-03, 1.32079700e-02, 6.94011119e-03, 1.55200692e-02,
       9.38685983e-03, 1.99464058e-02, 2.84212852e-02, 5.21084431e-03,
       4.89978610e-03, 4.06883197e-03, 1.15506630e-02, 8.80524904e-03,
       1.99608487e-02, 1.69938521e-03, 1.36802217e-02, 1.07207767e-02,
       9.30307898e-03, 1.82298416e-02, 1.50239293e-02, 5.85515574e-02,
       9.60227562e-03, 4.53166705e-04, 5.07299778e-05, 5.69922887e-03,
       2.05274871e-02, 2.99778819e-03, 7.37745915e-03, 1.35673666e-02,
       1.14705049e-02, 9.17620769e-03, 9.65024623e-03, 8.31894211e-03,
       2.17876363e-02, 1.10705186e-02, 3.71906517e-03, 1.71143738e-02,
       8.06172634e-03, 8.97265838e-03, 1.00184340e-02, 1.35664754e-02,
       1.11458008e-02, 1.50181652e-02, 1.07662105e-02, 6.44745413e-03,
       6.55489795e-03, 2.31837857e-02, 6.31867483e-03, 2.49327826e-02,
       1.06414655e-02, 5.03687860e-03, 8.56981769e-03, 1.09090873e-02,
       8.38453993e-03, 9.65330979e-03, 7.36718551e-03, 1.20637640e-02,
       6.14543994e-03, 7.45962751e-03, 7.62274619e-03, 7.62244677e-03,
       6.46657051e-04, 9.29602858e-03, 3.16997933e-03, 1.30947251e-02,
       0.00000000e+00, 8.87326300e-03, 5.63744384e-03, 1.25365296e-02,
       7.54849755e-03, 1.36631911e-02, 1.10685976e-02, 1.17101220e-02,
       8.77774698e-03, 1.40995477e-02, 3.00677150e-02, 3.95021319e-02,
       2.21721538e-02, 9.41752622e-03, 1.07467850e-02, 7.41990521e-03,
       0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
       0.00000000e+00])

In [27]:
dic1={}
for i in range(len(clf.feature_importances_)):
    dic1[data.columns[i]]=clf.feature_importances_[i]

In [28]:
data_watch=pd.DataFrame({'feature':list(dic1.keys()),'importance':list(dic1.values())})

In [29]:
data_watch.sort_values(by='importance',ascending=False)

                                       feature  importance
23                            history_fail_fee    0.058552
79     trans_fail_top_count_enum_last_12_month    0.039502
3                                  apply_score    0.037175
78                  trans_days_interval_filter    0.030068
10                           consfin_max_limit    0.028421
51                                 loans_score    0.024933
49                         loans_overdue_count    0.023184
80      trans_fail_top_count_enum_last_1_month    0.022172
36                     latest_three_month_loan    0.021788
28                       latest_one_month_fail    0.020527
16               consume_top_time_last_6_month    0.019961
9                         consfin_credit_limit    0.019946
1                                          abs    0.018262
21                     historical_trans_amount    0.018230
39                                 loans_count    0.017114
7                            consfin_avg_limit    0.015520
0                                   Unnamed: 0    0.015293
22                        historical_trans_day    0.015024
45                             loans_long_time    0.015018
77                         trans_days_interval    0.014100
18                                      custid    0.013680
73                        trans_activity_month    0.013663
31                            latest_query_day    0.013567
43                            loans_latest_day    0.013566
5                      avg_price_last_12_month    0.013208
67                        repayment_capability    0.013095
71                top_trans_count_last_1_month    0.012537
59  pawns_auctions_trusts_consume_last_6_month    0.012064
75           trans_amount_increase_rate_lately    0.011710
14              consume_mini_time_last_1_month    0.011551
..                                         ...         ...
72                          trans_activity_day    0.007548
61                         query_finance_count    0.007460
83                 trans_top_time_last_6_month    0.007420
30                        latest_one_month_suc    0.007377
58  pawns_auctions_trusts_consume_last_1_month    0.007367
6            avg_price_top_last_12_valid_month    0.006940
48                     loans_org_count_current    0.006555
47                    loans_org_count_behavior    0.006447
50                         loans_product_count    0.006319
60                            query_cash_count    0.006145
27                      latest_one_month_apply    0.005699
70       take_amount_in_later_12_month_highest    0.005637
4              avg_consume_less_12_valid_month    0.005236
11                  consfin_org_count_behavior    0.005211
53                          low_volume_percent    0.005037
12                   consfin_org_count_current    0.004900
13                       consfin_product_count    0.004069
38                            loans_cash_count    0.003719
66                           regional_mobility    0.003170
29                       latest_one_month_loan    0.002998
17            cross_consume_count_last_1_month    0.001699
64         railway_consume_count_last_12_month    0.000647
25                                is_high_user    0.000453
26          jewelry_consume_count_last_6_month    0.000051
86                                        三线城市    0.000000
87                                        二线城市    0.000000
68                                      status    0.000000
85                                        一线城市    0.000000
84                                  transd_mcc    0.000000
88                                        其他城市    0.000000

[89 rows x 2 columns]

In [72]:
use=data_watch.sort_values(by='importance',ascending=False).iloc[0:40,:]
use_columns=list(use['feature'].values)

In [74]:
use_columns.append('status')

In [30]:
#分X,Y值和训练集测试集
from sklearn.model_selection import train_test_split

In [75]:
data_totrain=data[use_columns]

In [76]:
X, y = data_totrain.drop(columns=['status'],axis=1),data_totrain['status']

In [31]:
x_train, x_test, y_train, y_test = train_test_split(data.drop(columns=['status'],axis=1,inplace=False).as_matrix(), data['status'].values, test_size=0.3, random_state=2018)

F:\anaconda\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.

In [32]:
from sklearn.linear_model.logistic import LogisticRegression

In [33]:
from sklearn.cross_validation import train_test_split, cross_val_score

F:\anaconda\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)

In [34]:
 from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,roc_auc_score

In [35]:
#逻辑回归
classifier=LogisticRegression()
classifier.fit(x_train,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [52]:
len(y_test)

2659

In [36]:
from sklearn.ensemble import RandomForestClassifier

In [37]:
rf=RandomForestClassifier()

In [38]:
rf.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [39]:
from xgboost.sklearn import XGBClassifier

In [40]:
xgb=XGBClassifier()

In [41]:
xgb.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='binary:logistic', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [42]:
f1_score_lst=[f1_score(y_test,classifier.predict(x_test)),f1_score(y_test,rf.predict(x_test)),f1_score(y_test,xgb.predict(x_test))]

F:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [43]:
accuracy_score_lst=[accuracy_score(y_test,classifier.predict(x_test)),accuracy_score(y_test,rf.predict(x_test)),accuracy_score(y_test,xgb.predict(x_test))]

F:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [44]:
precision_score_lst=[precision_score(y_test,classifier.predict(x_test)),precision_score(y_test,rf.predict(x_test)),precision_score(y_test,xgb.predict(x_test))]

F:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [45]:
recall_score_lst=[recall_score(y_test,classifier.predict(x_test)),recall_score(y_test,rf.predict(x_test)),recall_score(y_test,xgb.predict(x_test))]

F:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [46]:
roc_auc_score_lst=[roc_auc_score(y_test,classifier.predict(x_test)),roc_auc_score(y_test,rf.predict(x_test)),roc_auc_score(y_test,xgb.predict(x_test))]

F:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:151: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
  if diff:

In [47]:
view = pd.DataFrame({'model':['lr','rf','xgb'],'f1_score':f1_score_lst,'accuracy_score':accuracy_score_lst,'precision_score':precision_score_lst,'recall_score':recall_score_lst,'roc_auc':roc_auc_score_lst})

In [48]:
view

  model  f1_score  accuracy_score  precision_score  recall_score   roc_auc
0    lr  0.000000        0.867995         0.000000      0.000000  0.497414
1    rf  0.403226        0.888680         0.636943      0.294985  0.635208
2   xgb  0.515888        0.902595         0.704082      0.407080  0.691040